# require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/**
    - db/schema.rb
    - db/migrate/**
    - examples/**
    - examples/db/schema.rb
    - examples/db/seeds.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
